module.exports = {
  roles: [
    { id: "red",   name: "Red",   },
    { id: "yellow", name: "Yellow", },
    { id: "green", name: "Green", },
    { id: "blue",  name: "Blue",  },
  ],
  objects: [
    {
      faces: ["checkers/board.png"],
      locked: true,
      x: 500,
      y: 200,
      width: 400,
      height: 400,
      snapZones: [
        { cellWidth: 50, cellHeight: 50 },
      ],
    },
    {
      id: "checkersPiece",
      prototype: true,
      width: 50,
      height: 50,
    },
    {
      id: "redPiece",
      prototype: true,
      prototypes: ["checkersPiece"],
      faces: [
        "checkers/red_pawn.png",
        "checkers/red_king.png",
      ],
    },
    {
      id: "blackPiece",
      prototype: true,
      prototypes: ["checkersPiece"],
      faces: [
        "checkers/black_pawn.png",
        "checkers/black_king.png",
      ],
    },
    {
      id: ""
    },
    { prototypes: ["redPiece"],   x: 550, y: 200},
    { prototypes: ["redPiece"],   x: 650, y: 200},
    { prototypes: ["redPiece"],   x: 750, y: 200},
    { prototypes: ["redPiece"],   x: 850, y: 200},
    { prototypes: ["redPiece"],   x: 500, y: 250},
    { prototypes: ["redPiece"],   x: 600, y: 250},
    { prototypes: ["redPiece"],   x: 700, y: 250},
    { prototypes: ["redPiece"],   x: 800, y: 250},
    { prototypes: ["redPiece"],   x: 550, y: 300},
    { prototypes: ["redPiece"],   x: 650, y: 300},
    { prototypes: ["redPiece"],   x: 750, y: 300},
    { prototypes: ["redPiece"],   x: 850, y: 300},
    { prototypes: ["blackPiece"], x: 500, y: 550},
    { prototypes: ["blackPiece"], x: 600, y: 550},
    { prototypes: ["blackPiece"], x: 700, y: 550},
    { prototypes: ["blackPiece"], x: 800, y: 550},
    { prototypes: ["blackPiece"], x: 550, y: 500},
    { prototypes: ["blackPiece"], x: 650, y: 500},
    { prototypes: ["blackPiece"], x: 750, y: 500},
    { prototypes: ["blackPiece"], x: 850, y: 500},
    { prototypes: ["blackPiece"], x: 500, y: 450},
    { prototypes: ["blackPiece"], x: 600, y: 450},
    { prototypes: ["blackPiece"], x: 700, y: 450},
    { prototypes: ["blackPiece"], x: 800, y: 450},

    {
      id: "d6",
      prototype: true,
      width: 25,
      height: 25,
      faces: [
        "dice/d6_1.png",
        "dice/d6_2.png",
        "dice/d6_3.png",
        "dice/d6_4.png",
        "dice/d6_5.png",
        "dice/d6_6.png",
      ],
    },
    { prototypes: ["d6"], x: 950, y: 400},
    { prototypes: ["d6"], x: 975, y: 400},

    {
      id: "card",
      prototype: true,
      x: 400,
      y: 400,
      width: 50,
      height: 70,
      back: "cards/back.png",
    },
    { prototypes: ["card"], front: "cards/fronts.png#"+( 0*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 1*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 2*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 3*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 4*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 5*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 6*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 7*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 8*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 9*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(10*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(11*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(12*560)+","+(0*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 0*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 1*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 2*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 3*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 4*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 5*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 6*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 7*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 8*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 9*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(10*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(11*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(12*560)+","+(1*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 0*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 1*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 2*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 3*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 4*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 5*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 6*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 7*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 8*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 9*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(10*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(11*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(12*560)+","+(3*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 0*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 1*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 2*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 3*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 4*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 5*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 6*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 7*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 8*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+( 9*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(10*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(11*560)+","+(2*780)+",560,780"},
    { prototypes: ["card"], front: "cards/fronts.png#"+(12*560)+","+(2*780)+",560,780"},

    {
      id: "uno",
      prototype: true,
      x: 400,
      y: 300,
      width: 50,
      height: 70,
      back: "uno/card_back.png",
    },
    { prototypes: ["uno"], front: "uno/blue_0.png"},
    { prototypes: ["uno"], front: "uno/blue_1.png"},
    { prototypes: ["uno"], front: "uno/blue_2.png"},
    { prototypes: ["uno"], front: "uno/blue_3.png"},
    { prototypes: ["uno"], front: "uno/blue_4.png"},
    { prototypes: ["uno"], front: "uno/blue_5.png"},
    { prototypes: ["uno"], front: "uno/blue_6.png"},
    { prototypes: ["uno"], front: "uno/blue_7.png"},
    { prototypes: ["uno"], front: "uno/blue_8.png"},
    { prototypes: ["uno"], front: "uno/blue_9.png"},
    { prototypes: ["uno"], front: "uno/blue_picker.png"},
    { prototypes: ["uno"], front: "uno/blue_reverse.png"},
    { prototypes: ["uno"], front: "uno/blue_skip.png"},
    { prototypes: ["uno"], front: "uno/green_0.png"},
    { prototypes: ["uno"], front: "uno/green_1.png"},
    { prototypes: ["uno"], front: "uno/green_2.png"},
    { prototypes: ["uno"], front: "uno/green_3.png"},
    { prototypes: ["uno"], front: "uno/green_4.png"},
    { prototypes: ["uno"], front: "uno/green_5.png"},
    { prototypes: ["uno"], front: "uno/green_6.png"},
    { prototypes: ["uno"], front: "uno/green_7.png"},
    { prototypes: ["uno"], front: "uno/green_8.png"},
    { prototypes: ["uno"], front: "uno/green_9.png"},
    { prototypes: ["uno"], front: "uno/green_picker.png"},
    { prototypes: ["uno"], front: "uno/green_reverse.png"},
    { prototypes: ["uno"], front: "uno/green_skip.png"},
    { prototypes: ["uno"], front: "uno/red_0.png"},
    { prototypes: ["uno"], front: "uno/red_1.png"},
    { prototypes: ["uno"], front: "uno/red_2.png"},
    { prototypes: ["uno"], front: "uno/red_3.png"},
    { prototypes: ["uno"], front: "uno/red_4.png"},
    { prototypes: ["uno"], front: "uno/red_5.png"},
    { prototypes: ["uno"], front: "uno/red_6.png"},
    { prototypes: ["uno"], front: "uno/red_7.png"},
    { prototypes: ["uno"], front: "uno/red_8.png"},
    { prototypes: ["uno"], front: "uno/red_9.png"},
    { prototypes: ["uno"], front: "uno/red_picker.png"},
    { prototypes: ["uno"], front: "uno/red_reverse.png"},
    { prototypes: ["uno"], front: "uno/red_skip.png"},
    { prototypes: ["uno"], front: "uno/yellow_0.png"},
    { prototypes: ["uno"], front: "uno/yellow_1.png"},
    { prototypes: ["uno"], front: "uno/yellow_2.png"},
    { prototypes: ["uno"], front: "uno/yellow_3.png"},
    { prototypes: ["uno"], front: "uno/yellow_4.png"},
    { prototypes: ["uno"], front: "uno/yellow_5.png"},
    { prototypes: ["uno"], front: "uno/yellow_6.png"},
    { prototypes: ["uno"], front: "uno/yellow_7.png"},
    { prototypes: ["uno"], front: "uno/yellow_8.png"},
    { prototypes: ["uno"], front: "uno/yellow_9.png"},
    { prototypes: ["uno"], front: "uno/yellow_picker.png"},
    { prototypes: ["uno"], front: "uno/yellow_reverse.png"},
    { prototypes: ["uno"], front: "uno/yellow_skip.png"},
    { prototypes: ["uno"], front: "uno/wild.png"},
    { prototypes: ["uno"], front: "uno/wild.png"},
    { prototypes: ["uno"], front: "uno/wild.png"},
    { prototypes: ["uno"], front: "uno/wild.png"},
    { prototypes: ["uno"], front: "uno/wild_four.png"},
    { prototypes: ["uno"], front: "uno/wild_four.png"},
    { prototypes: ["uno"], front: "uno/wild_four.png"},
    { prototypes: ["uno"], front: "uno/wild_four.png"},

    {
      id: "handScreenHorizontal",
      prototype: true,
      locked: true,
      x: 400,
      width:  600,
      height: 100,
      hideFaces: ["front"],
      snapZones: [{}],
    },
    { prototypes: ["handScreenHorizontal"], y:   0, visionWhitelist: ["red"  ], backgroundColor: "rgba(224,136,58,alpha)", labelPlayerName: "red",   },
    // color hexes:
    // BOARD COLOR: #D7DEC2
    // RED: #E088E3A
    // PURPLE: #7541E30
    // YELLOW: #E0D255
    // BLUE: #79DSDE
    { prototypes: ["handScreenHorizontal"], y: 700, visionWhitelist: ["blue"], backgroundColor: "rgba(117,65,224,alpha)",   labelPlayerName: "blue", },

    {
      id: "handScreenVertical",
      prototype: true,
      locked: true,
      y: 100,
      width:  100,
      height: 600,
      hideFaces: ["front"],
      snapZones: [{}],
    },
    { prototypes: ["handScreenVertical"], x: 0, visionWhitelist: ["yellow"], backgroundColor: "rgba(224,210,85,alpha)",   labelPlayerName: "yellow", },
    { prototypes: ["handScreenVertical"], x: 1315, visionWhitelist: ["green"], backgroundColor: "rgba(121,213,222,alpha)",   labelPlayerName: "green", },
  ],
};
